---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger-fe
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-fe-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: nodejs-pipeline
        params:
          - name: repo-url
            value: https://github.com/cloud-native-garage-method-cohort/emea-5-project-squad2-fe.git
          - name: branch-name
            value: main
          - name: image-repo
            value: quay.io/tkaatz/squad2-fe
          - name: app-name
            value: backend
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 300Mi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: vcs-trigger-fe
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vcs-trigger-fe
spec:
  serviceAccountName: vcs-trigger
  triggers:
    - bindings:
        - ref: vcs-trigger-fe
      template:
        name: vcs-trigger-fe
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vcs-trigger-fe
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-vcs-trigger-fe
    weight: 100
