---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-node-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: nodejs-pipeline
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 300Mi
  params:
  - name: repo-url
    value: https://github.com/13yo/express-sample-app.git
  - name: branch-name
    value: main
  - name: image-repo
    value: quay.io/tkaatz/hello-web
  - name: app-name
    value: express-sample-app