---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-fe-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: nodejs-pipeline
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 300Mi
  params:
  - name: repo-url
    value: https://github.com/cloud-native-garage-method-cohort/emea-5-project-squad2-fe.git
  - name: branch-name
    value: main
  - name: image-repo
    value: quay.io/tkaatz/squad2-fe
  - name: app-name
    value: backend